name: Assignment Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 24f2003563@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Second Step
        run: echo "Workflow completed"
